CREATE TABLE GrupoA (nome VARCHAR(20) PRIMARY KEY);
CREATE TABLE GrupoB (nome VARCHAR(20) PRIMARY KEY);

INSERT INTO GrupoA VALUES("BRASIL");
INSERT INTO GrupoA VALUES("HOLANDA");
INSERT INTO GrupoA VALUES("MÉXICO");
INSERT INTO GrupoA VALUES("EUA");

INSERT INTO GrupoB VALUES("ITALIA");
INSERT INTO GrupoB VALUES("ARGENTINA");
INSERT INTO GrupoB VALUES("JAPAO");
INSERT INTO GrupoB VALUES("CUBA");

